### ISSUE TITLE
Fails on get dependencies

### ISSUE THREAD

**Issue by majioa** [wojtekmach/mini_repo#10]
I'm doing an installation according the manuals but it fails on get deps stage:
```
$ mix deps.get
** (CompileError) config/config.exs:1: module Config is not loaded and could not be found
    (elixir) lib/code.ex:232: Code.eval_string/3
    (mix) lib/mix/config.ex:220: Mix.Config.eval!/2
```
I've elixir v 1.9.2

**Comment by wojtekmach** [comment]
Not sure how is this possible given `Config` module is part of Elixir as of v1.9. Could you paste the exact steps you're taking along with output of `elixir --version`?

**Comment by majioa** [comment]
It seems the new version wasn't pick up. Currently is ok
