### ISSUE TITLE
Always tries to publish to hexpm

### ISSUE THREAD

**Issue by anthonator** [wojtekmach/mini_repo#14]
Whenever I try to publish to my hosted `mini_repo` it always tries to publish to `hexpm`.

When I `mix hex.publish package`

I always get the message.

```
Publishing package to public repository hexpm.
not found
```

Here's my `mix.exs`

```
defmodule HelloRepo.MixProject do
  use Mix.Project

  def project do
    [
      app: :hello_repo,
      description: "Hello, repo!",
      version: "0.0.0",
      elixir: "~> 1.9",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      hex: hex(),
      package: package()
    ]
  end

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  defp deps do
    []
  end

  defp hex do
    [
      api_url: "...",
      api_key: "..."
    ]
  end

  defp package do
    [
      licenses: [],
      links: %{}
    ]
  end
end
```

**Comment by wojtekmach** [comment]
Could you paste output of `mix hex.info`? Make sure you’re on latest version.

**Comment by wojtekmach** [comment]
I think the problem might be that we don’t show in Hex client that you’re not actually pushing to hex.pm and that’s confusing (and arguably a bug) 

I’d temporarily add `hex.pm 0.0.0.0` to `/etc/hosts` and see if it works :)

**Comment by ericmj** [comment]
> I think the problem might be that we don’t show in Hex client that you’re not actually pushing to hex.pm and that’s confusing (and arguably a bug)

Definitely, this should be made very clear.

**Comment by ericmj** [comment]
You are getting a 404 error which means you probably have `api_url` configured incorrectly.

**Comment by anthonator** [comment]
The repo is configured exactly how it says I should in the README.

```
https://<domain>/api/repos/<repo>
```

If I copy and paste the `api_url` into my browser I get an unauthorized error and not a 404.

**Comment by anthonator** [comment]
Here's the output of my `mix hex.info`

Hex:    0.20.1
Elixir: 1.9.2
OTP:    22.0.7

**Comment by ericmj** [comment]
Can you show the value you have for `api_url` and how you configured mini_repo?

**Comment by anthonator** [comment]
I'd prefer to not share my domain and repo. What I posted above was a copy/paste. I just removed the sensitive bits.

What would be valuable to see for sharing my configuration? Seeing my `release.exs`?

**Comment by ericmj** [comment]
You are getting a 404 error so that means you can connect to the server (assuming you are connecting to mini_repo) but you have the wrong URL path. It is important you have configured the same repository name in your mini_repo config and api_url.

Unfortunately if you cannot show your configuration we cannot help checking if it is correct. Does mini_repo produce any output when you try to publish?

EDIT: You may need to change the logger level to get output.

**Comment by anthonator** [comment]
When I try to publish I get a 404 at this path.

```
/api/repos/<repo>/users/me
```

I'm assuming this is probably an issue with `api_key`?

**Comment by anthonator** [comment]
I do have `MINI_REPO_AUTH_TOKEN` configured on our server.

**Comment by anthonator** [comment]
Also `MINI_REPO_REPO_NAME` matches the repo I have in `api_url`.

**Comment by anthonator** [comment]
Here's my `release.exs` if that's helpful.

```elixir
import Config

config :ex_aws,
  access_key_id: System.fetch_env!("AWS_ACCESS_KEY_ID"),
  secret_access_key: System.fetch_env!("AWS_SECRET_ACCESS_KEY"),
  json_codec: Jason

config :mini_repo,
  port: String.to_integer(System.get_env("PORT", "4000")),
  url: System.get_env("MINI_REPO_URL", "http://localhost:4000")

repo_name = String.to_atom(System.get_env("MINI_REPO_REPO_NAME", "test_repo"))

private_key =
  System.get_env("MINI_REPO_PRIVATE_KEY") ||
    File.read!(Path.join([:code.priv_dir(:mini_repo), "test_repo_private.pem"]))

public_key =
  System.get_env("MINI_REPO_PUBLIC_KEY") ||
    File.read!(Path.join([:code.priv_dir(:mini_repo), "test_repo_public.pem"]))

auth_token =
  System.get_env("MINI_REPO_AUTH_TOKEN") ||
    raise """
    Environment variable MINI_REPO_AUTH_TOKEN must be set.
    You can generate secret e.g. with this:
        iex> length = 32
        iex> :crypto.strong_rand_bytes(length) |> Base.encode64 |> binary_part(0, length)
        "Xyf..."
    """

    store =
      {MiniRepo.Store.S3,
       bucket: System.fetch_env!("S3_BUCKET"),
       options: [
         region: System.fetch_env!("S3_REGION")]
       }

config :mini_repo,
  auth_token: System.fetch_env!("MINI_REPO_AUTH_TOKEN"),
  repositories: [
    "#{repo_name}": [
      private_key: private_key,
      public_key: public_key,
      store: store
    ],
    hexpm_mirror: [
      store: store,
      upstream_name: "hexpm",
      upstream_url: "https://repo.hex.pm",

      # https://hex.pm/docs/public_keys
      upstream_public_key: """
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApqREcFDt5vV21JVe2QNB
      Edvzk6w36aNFhVGWN5toNJRjRJ6m4hIuG4KaXtDWVLjnvct6MYMfqhC79HAGwyF+
      IqR6Q6a5bbFSsImgBJwz1oadoVKD6ZNetAuCIK84cjMrEFRkELtEIPNHblCzUkkM
      3rS9+DPlnfG8hBvGi6tvQIuZmXGCxF/73hU0/MyGhbmEjIKRtG6b0sJYKelRLTPW
      XgK7s5pESgiwf2YC/2MGDXjAJfpfCd0RpLdvd4eRiXtVlE9qO9bND94E7PgQ/xqZ
      J1i2xWFndWa6nfFnRxZmCStCOZWYYPlaxr+FZceFbpMwzTNs4g3d4tLNUcbKAIH4
      0wIDAQAB
      -----END PUBLIC KEY-----
      """,

      # only mirror following packages
      only: ~w(decimal),

      # 5min
      sync_interval: 5 * 60 * 1000
    ]
  ]
```

**Comment by ericmj** [comment]
> When I try to publish I get a 404 at this path.
> /api/repos/<repo>/users/me

That's fine, what's the next path that is hit?

**Comment by anthonator** [comment]
No other path is hit.

Here are the logs. I waited about 30 seconds before capturing this to ensure nothing else happens.

```
2019-10-31T11:59:03.969692+00:00 heroku[router]: at=info method=GET path="/api/repos/<repo>/users/me" host=<host> request_id=657c44df-b625-4ec4-80c1-208e8c7fe00c fwd="24.172.163.138" dyno=web.1 connect=1ms service=1ms status=404 bytes=178 protocol=https
2019-10-31T11:59:03.963372+00:00 app[web.1]: 
2019-10-31T11:59:03.963391+00:00 app[web.1]: 11:59:03.962 [info]  GET /api/repos/<repo>/users/me
2019-10-31T11:59:03.963399+00:00 app[web.1]: 
2019-10-31T11:59:03.963402+00:00 app[web.1]: 11:59:03.963 [info]  Sent 404 in 64µs
```

**Comment by ericmj** [comment]
What happens after you get the following output? Does it hang?

```
Publishing package to public repository hexpm.
not found
```

**Comment by anthonator** [comment]
Here's what I see.

<img width="542" alt="Screen Shot 2019-10-31 at 8 04 21 AM" src="https://user-images.githubusercontent.com/420061/67945364-17e44900-fbb5-11e9-8daa-d5564c2d309b.png">

**Comment by ericmj** [comment]
You need to write `Y [ENTER]` after `Proceed? [Yn]`.

**Comment by anthonator** [comment]
I don't want to publish to `hexpm`. I want to publish to our private `mini_repo`.

The above image shows.

```
Publishing package to public repository hexpm.
```

**Comment by ericmj** [comment]
The output is not correct as @wojtekmach said:

> I think the problem might be that we don’t show in Hex client that you’re not actually pushing to hex.pm and that’s confusing (and arguably a bug)

You can proceed with publishing, it will publish to your private repo.

**Comment by anthonator** [comment]
I'll give it a try! 😅

**Comment by anthonator** [comment]
It worked!

I'll submit a PR to the README to call this out.

Thanks for all your help!

**Comment by ericmj** [comment]
> I'll submit a PR to the README to call this out.

Please open an issue on https://github.com/hexpm/hex instead.

**Comment by anthonator** [comment]
Will do
