### ISSUE TITLE
Upgrading to hex_core 0.6.1 breaks everything

### ISSUE THREAD

**Issue by anthonator** [wojtekmach/mini_repo#17]
I just did an upgrade of `hex_core` to 0.6.1 and everything seem to have stopped working. You should be able to see the issues by running the test suite.

**Comment by ericmj** [comment]
It's not supposed to work with hex_core v0.6.1. The requirement in `mix.exs` is `{:hex_core, "~> 0.5.0"}` so you v0.6.1 will not be fetched.
