### ISSUE TITLE
Feature Request - On demand hexpm_mirror caching

### ISSUE THREAD

**Issue by cburman01** [wojtekmach/mini_repo#18]
@wojtekmach What would you think about having an option to fetch packages from hexpm on demand instead of specifying only the packages to download. 

I'm thinking it would work something like Nexus where packages are downloaded when they are requested.  

The reason I think this request is needed is because its difficult to list every package that we may need using mini_repo from hexpm with the :only option.  It would allow us to fetch all packages internally on demand and our deps.get would be faster because we are relying on cache from mini_repo instead of hexpm public. (For our CI since local dev caches). 

I have been playing around with the code and this shouldn't be very hard to accomplish. 

From what I can tell, packages are fetched with two requests from `hex.package fetch package version`

` /repos/hexpm_mirror/packages/<package_name>`
` /repos/hexpm_mirror/tarballs/<tarball>`

Currently these are matched with the Plug.Static: 
```
  plug Plug.Static,
    at: "/repos",
    from: {:mini_repo, "data/repos"}
```

I would propose that we add two new endpoint matches something like:
`  get "/repos/hexpm_mirror/packages/:name" ` 
and 
`get  "/repos/hexpm_mirror/tarballs/:tarball"`

We then manually check if the package exists in the `Application.app_data(:mini_repo) "data/hexpm_mirror/..." ` location.  If that exists great then  send_file (conn, 200, path) the package and the tarball.. But if not, we go fetch the package from hex and if it exists, write the file and serve it up.  Then all future requests for the same package and version will be found and served up. 

We could accomplish pretty easy with a callback into server.ex and a little code to fetch a single package or a list of packages.  

What do you think? I'd be happy to code this, but wanted to first see if you would want a feature like this.  Sorry if this was a little all over the place.

**Comment by wojtekmach** [comment]
Yes, this is definitely wanted change, PR appreciated! Implementation-vise I would like to start with a new module (rather than changing existing mirror one)

**Comment by cburman01** [comment]
Awesome, working on it now. I appreciate the feedback. Will open a PR for your review and feedback soon.

**Comment by ericmj** [comment]
> Then all future requests for the same package and version will be found and served up.

You also need a way to refresh the package's registry file when new versions have been published.

**Comment by cburman01** [comment]
Ok. I think I have that accounted for when the sync loop starts. It will pull the parsed bin file mirror.registry to run a diff based on those versions and the ones it gets from hex. 

If new packages are added, the registry gets updated and the sync loop will account for the new package.  

It’s pretty close to the way it was where the only world list was being passed it.

**Comment by cburman01** [comment]
So I have this working, but I have a couple concerns with the approach. 

When a dependency is fetched, it seems hex will call the mirror URL `/packages/name` (grabbing the package file) and at the same time a call to grab the tarball `tarballs/:tarball`.  The problem is: 
If the package does not exist on disk, the package file will also not exist. The only option I have is to go out and grab every version then return the package file (because version number is not included in the parms to the package request).. This work all well and good.. But I am concerned about packages with a lot of releases like plug. The time to grab all releases will certainly grow overtime. I would rather just grab the version we need initially, then let sync fetch the rest based off the diff.  

The other request that grabs the tarball does include the version number, but these request appear to be in parallel so I can't control which one comes in first. 

Any advice?

**Comment by ericmj** [comment]
You can fetch and cache `tarballs/:tarball` on demand like you fetch and cache `/packages/name` on demand. Why do you have to fetch all versions of the package?

> The other request that grabs the tarball does include the version number, but these request appear to be in parallel so I can't control which one comes in first.

The requests are not in parallel. Hex will first the registry files for all packages then fetch all the tarballs. The tarball has the version in path, for example `tarballs/phoenix-1.2.3.tar`.

**Comment by cburman01** [comment]
Yeah I can get the version from the tarball request with no problem. But how do I know the version when the package request comes in.  
Example first request for fetching plug_cowboy v2.1.0:` /repos/hexpm_mirror/packages/plug_cowboy` 

The package file located in: data/repos/hexpm_mirror/packages/plug_cowboy doesnt exist at that time. 

Also, since no versions  exist on our disk at that time, i don't know which version to get.  It's not until the tarball request where I know the version number.

**Comment by cburman01** [comment]
@ericmj I think I figured it out :) I wasnt thinking about versions and packages as separate entities!

**Comment by cburman01** [comment]
Ref: https://github.com/wojtekmach/mini_repo/pull/19
