### ISSUE TITLE
Getting 404 when trying to pull package using S3 adapter

### ISSUE THREAD

**Issue by anthonator** [wojtekmach/mini_repo#20]
When I try to `mix deps.get` packages hosted on our private `mini_repo` we get a 404 . Looking at our server logs I see `/repos/our_repo/packages/our_package` but it returns a 404. When I look at our S3 bucket I can see the packages and tarballs. I have the public access policy documented in `releases.exs` on the bucket. I've turned off all public access restrictions to the bucket.

Not sure what I'm doing wrong.

I'm assuming `mini_repo` proxies all package fetches to S3. Is that the case? Should I be going straight to S3?

**Comment by wojtekmach** [comment]
> I'm assuming mini_repo proxies all package fetches to S3. Is that the case? Should I be going straight to S3?

Yes, you should be going straight to S3, see:

https://github.com/wojtekmach/mini_repo/blob/613c955f5fa9af18113857047320d3246c1fd852/lib/mini_repo/store/s3.ex#L59:L62

FWIW that's basically how repo.hex.pm is deployed, the actual tarballs are on S3 with Fastly in front :)

**Comment by anthonator** [comment]
That was it! My apologies. I looked for that in the docs and didn't see it. Apparently I didn't look hard enough. Thank you!
