### ISSUE TITLE
Feature request: Public Key GET Endpoints

### ISSUE THREAD

**Issue by asummers** [wojtekmach/mini_repo#22]
When adding new repos to Mini Repo, we already have to specify the public and private keys in the list of repositories. Adding one of these as an upstream hex repo locally requires sharing the same key out of band. It would be terrific if there was an endpoint where we could ask the upstream repo for its public key (thinking something along the lines of `GET /api/repos/:repo/public_key`), so that the setup locally can be done by running a curl command entirely in band of the upstream repo. This is analogous to the key being listed on `https://hex.pm/docs/public_keys` for the original hex repo.

**Comment by wojtekmach** [comment]
This is a great idea.

> thinking something along the lines of GET /api/repos/:repo/public_key

My initial reaction is to keep it close with the other registry resources (like /name, /versions, etc, see https://github.com/hexpm/specifications/blob/master/registry-v2.md), so on a typical minirepo installation that would be:

```
GET https://localhost:4000/repos/acme/public_key
# or more explicit
GET https://localhost:4000/repos/acme/public_key.pem
```

this is a separate discussion but I think this could even be part of the Registry v2 spec (cc @ericmj), so Hex.pm's keys would be at:

```
GET https://repo.hex.pm/public_key
GET https://repo.hex.pm/repos/acme/public_key
```

**Comment by asummers** [comment]
Given that the config is just the string of the key itself, is it always guaranteed that it will be a `.pem` file? I am fine with that being the endpoint but for futureproofing, either forcing the user to be explicit about file type somewhere in the config, or just eliding entirely in the URL might be better. I'm very okay with it not living under `/api` though!
