### ISSUE TITLE
Guidance / Documentation Request For Certs 

### ISSUE THREAD

**Issue by asummers** [wojtekmach/mini_repo#23]
Hex allows overriding a cert path (via `cacerts_path` or `HEX_CACERTS_PATH` env variable) to point to a specific PEM file, which works when attempting to pull just private files (`repo: "my_repo"`) from a mini repo using a custom SSL cert. How then do you continue to use the SSL cert for the original hex packages? You either get an SSL error for `mix deps.get` for private packages, or an SSL error for the public packages. One can elect to use `unsafe_https` but this is an unsatisfying solution. It seems as though the `CACERTS` should somehow tie to the repo  perhaps?

**Comment by ericmj** [comment]
The PEM file can have multiple certificates. So you can include both the certificate your private repo uses and the one repo.hex.pm uses.

**Comment by asummers** [comment]
Ah fair enough. That seems reasonable.
