### ISSUE TITLE
mix hex.search support?

### ISSUE THREAD

**Issue by asummers** [wojtekmach/mini_repo#27]
https://github.com/hexpm/hex/blob/master/lib/hex/api/package.ex#L12 seems to be calling a `GET <hex_api_url>/packages` URL which `mini_repo` does not support currently. That does not seem to be part of the [spec](https://github.com/hexpm/specifications/blob/master/endpoints.md) though so I am unsure what the proper resolution here is.

As a workflow complication, I'm imagining a user having several separate `mini_repo` instances which would all need to be searched simultaneously, and may not be on the same server or even intranet, so the right thing to do would probably be to improve `hex` to support multi-repo search by (perhaps) using repo URLs in some capacity versus the `:api_url` config.

**Comment by wojtekmach** [comment]
Currently we're supporting the minimal subset of HTTP API (https://github.com/hexpm/specifications/blob/master/http_api.md) that is needed for publishing and there are no plans to go beyond that. To support search in particular we'd need to store package metadata (description etc) and for now we're just storing the bare minimum that is needed to build the registry (https://github.com/hexpm/specifications/blob/master/registry-v2.md).
