### ISSUE TITLE
Implement api key

### ISSUE THREAD

**Issue by bcardarella** [wojtekmach/mini_repo#3]
I realize mini_repo is meant to be a simple hex, and it is great that it starts to address adoption concerns for Enterprise. At certain Enterprise scale different departments of orgs will and should have access control to self-hosted package hosts. Excluding the api key could be viewed as a security concern and become a non-starter as a self-hosted solution.

I would advocate for an opt-in for api key. Keep the default simple as it currently is. With a config option to generate / issue api keys for orgs that require that additional access control layer.

**Comment by wojtekmach** [comment]
By access control do you mean being able to just publish packages, or fetch packages? Or both? Should the access control be per repository (one mini_hex installation may support multiple)? I think each org may have a different answer to these and for that reason I'm wary as that'd be against the goal of the project. The goal is to be a starting point that folks can easily customise for their needs, it's not meant to be an off-the-shelf solution, there's some coding required.

That being said, I'd be ok with adding a very simple auth which would be a shared secret between the server and the client and it would only limit publishing packages. @bcardarella what do you think?

**Comment by bcardarella** [comment]
I cannot speak to how every org would want to host, but for some of our clients that use self-hosted npm mirrors each dept is responsible for the infrastructure, hosting, and content of the mirrors. Because the IP may be accessible by employees that aren't NDA'd into that department access control in the form of creds or api keys is necessary to prevent read/write access.

**Comment by ericmj** [comment]
We can create a behavior for authentication adapters. This way everyone can implement their own authentication that fits their organization, since as you suggest some may want to use API keys and others other forms of credentials.

**Comment by wojtekmach** [comment]
We've added basic token support, see e.g.: https://github.com/wojtekmach/mini_repo/blob/1b7a6bcbcc80f69ebdda36697c8d252a6cba9d9d/config/releases.exs#L18. No plans to extend it beyond that at the moment.
