### ISSUE TITLE
hex search only returns results from hex.pm mirror, never local repo

### ISSUE THREAD

**Issue by geib** [wojtekmach/mini_repo#34]
I am evaluating mini_repo for hosting internal hex packages and I have verified that "publish" and "fetch" of deps works but I have not been able to get "search" working against the local repo. When I do a "rebar3 hex search baz"  I receive no results after publishing baz and then using baz as dep in another project. Also I see it in the repo directory of the server.

**Comment by ericmj** [comment]
That seems like a configuration issue with rebar3 but mini_repo does not provide a search endpoint so it would not work.

**Comment by wojtekmach** [comment]
As Eric said above, search endpoint is not part of mini_repo.
