### ISSUE TITLE
Could not start mini_repo with aws store.

### ISSUE THREAD

**Issue by collegeimprovements** [wojtekmach/mini_repo#38]
Our config file is as follows: (we copied it from https://github.com/wojtekmach/mini_repo/blob/master/lib/mini_repo/store/s3.ex#L22-L27)
``` 
config :ex_aws,
  access_key_id: "OUR-AWS-ACCESS-KEY",
  secret_access_key: "OUR-AWS-SECRETE-KEY",
  json_codec: Jason

store =
  {MiniRepo.Store.S3,
   bucket: "minirepo",
   options: [
     region: "ap-southeast-1"
   ]}
```

This gives the following error. And project refuses to start.
```
** (EXIT) an exception was raised:
        ** (ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {"content-length", 0}
            (elixir 1.11.2) lib/keyword.ex:475: Keyword.keys/1
            (ex_aws 2.1.1) lib/ex_aws/auth.ex:163: ExAws.Auth.build_canonical_request/5
            (ex_aws 2.1.1) lib/ex_aws/auth.ex:146: ExAws.Auth.signature/8
            (ex_aws 2.1.1) lib/ex_aws/auth.ex:130: ExAws.Auth.auth_header/7
            (ex_aws 2.1.1) lib/ex_aws/auth.ex:45: ExAws.Auth.headers/6
            (ex_aws 2.1.1) lib/ex_aws/request.ex:29: ExAws.Request.request_and_retry/7
            (ex_aws 2.1.1) lib/ex_aws/operation/s3.ex:39: ExAws.Operation.ExAws.Operation.S3.perform/2
            (mini_repo 0.2.0) lib/mini_repo/store/s3.ex:113: MiniRepo.Store.S3.fetch/3
** (Mix) Could not start application mini_repo: MiniRepo.Application.start(:normal, []) returned an error: shutdown: failed to start child: MiniRepo.Repository.Server
    ** (EXIT) an exception was raised:
        ** (ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {"content-length", 0}
            (elixir 1.11.2) lib/keyword.ex:475: Keyword.keys/1
            (ex_aws 2.1.1) lib/ex_aws/auth.ex:163: ExAws.Auth.build_canonical_request/5
            (ex_aws 2.1.1) lib/ex_aws/auth.ex:146: ExAws.Auth.signature/8
            (ex_aws 2.1.1) lib/ex_aws/auth.ex:130: ExAws.Auth.auth_header/7
            (ex_aws 2.1.1) lib/ex_aws/auth.ex:45: ExAws.Auth.headers/6
            (ex_aws 2.1.1) lib/ex_aws/request.ex:29: ExAws.Request.request_and_retry/7
            (ex_aws 2.1.1) lib/ex_aws/operation/s3.ex:39: ExAws.Operation.ExAws.Operation.S3.perform/2
            (mini_repo 0.2.0) lib/mini_repo/store/s3.ex:113: MiniRepo.Store.S3.fetch/3
```

**Comment by collegeimprovements** [comment]
Hi @wojtekmach This commit fixed the issue but somehow it broke the whole aws thing.
If you can guide me, I can try fixing it.

Steps to reproduce: 
1. mix new <project_name> and configure repo with `mix hex.repo add hexpm_mirror http://localhost:4000/repos/hexpm_mirror` command.
2. Add any package in its mix.exs file
```
      {:nimble_parsec, "~> 1.1", repo: "hexpm_mirror"},
      {:nimble_options, "~> 0.3.5", repo: "hexpm_mirror"}
```
3. Whitelist packages of step-2 in mini_repo (`only` key). Configure aws with minirepo.
4. Start  minirepo
5. Try `mix deps.get` from the project created in step-1.

The error will be: 
```
Failed to fetch record for 'hexpm_mirror/nimble_options' from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
** (Mix) No package with name nimble_options (from: mix.exs) in registry
```

I can try fixing it, where should i look ?

Should we re-open this issue?

**Comment by wojtekmach** [comment]
looks like the mirror didn't fetch these upstream packages for some reason and thus they're not available for download when you try to fetch them from your new project. Try finding out why they haven't been downloaded, look at logs and into your store whether the tarballs are there.

**Comment by collegeimprovements** [comment]
Packages are there in s3 repo.  These are the full logs.

```
Failed to fetch record for 'hexpm_mirror/nimble_options' from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
** (Mix) No package with name nimble_options (from: mix.exs) in registry
```

The linking between s3 and minirepo-get is broken somehow. I'll try to debug it more and keep you updated.

**Comment by wojtekmach** [comment]
I believe this is the log from the project that runs `mix deps.get`. Instead look into your minirepo's installation logs to see whether nimble_options was successfully downloaded in the first place.

**Comment by collegeimprovements** [comment]
Yes. I can see the nimble_options and all the packages mentioned in `only` key in config file.
I saw these packages in minirepo's log as well when they got downloaded first time.

I nuked it multiple times, changed the aws-s3-bucket and tried again. 
Everytime, package is getting downloaded successfully. I can see them in minirepo logs and on s3 bucket.

But when we try to install these packages, the above error persists. 
Probably some kind of linking related problem.

**Comment by ericmj** [comment]
Note that the error "Failed to fetch record for 'hexpm_mirror/nimble_options' from registry" happens because it failed to download the registry file for the package, not because it failed to download the package tarball. Maybe you can try manually rebuilding the registry with `MiniRepo.Repository.Server.rebuild`.

**Comment by collegeimprovements** [comment]
I tried killing several process and tried few other ways but could not fix it.

Since, it's deprecated repo, it would be too much to ask for support. 
We will shift to `hex-registry-build` for custom repos once it's released.

And for mirroring purpose, `mini_repo` with local store is working great. 

Thanks a lot @wojtekmach , @ericmj  for your awesome work.
