### ISSUE TITLE
timeout errors

### ISSUE THREAD

**Issue by collegeimprovements** [wojtekmach/mini_repo#39]
I've relatively small set of libs to mirror. I've the following in my config file.
```
      # only mirror following packages
      only: ~w(decimal nimble_csv csv ex_aws ex_aws_s3),
```

But we get a lot of `timeout` errors and hence it never goes beyond `csv` package. 
After errors it restarts but it starts again from the start. And then again `timeout` error occurs on `csv` package only.

``` 
19:21:54.360 [error] GenServer :hexpm_mirror terminating
** (stop) exited in: Task.Supervised.stream(5000)
    ** (EXIT) time out
    (elixir 1.11.2) lib/task/supervised.ex:304: Task.Supervised.stream_reduce/7
    (elixir 1.11.2) lib/enum.ex:3461: Enum.reduce/3
    (mini_repo 0.2.0) lib/mini_repo/mirror/server.ex:106: MiniRepo.Mirror.Server.sync_created_packages/3
    (mini_repo 0.2.0) lib/mini_repo/mirror/server.ex:62: MiniRepo.Mirror.Server.sync/1
    (mini_repo 0.2.0) lib/mini_repo/mirror/server.ex:28: MiniRepo.Mirror.Server.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:431: :gen_server.loop/7
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :sync}
State: %MiniRepo.Mirror{name: "hexpm_mirror", only: ["decimal", "nimble_csv", "csv", "ex_aws", "ex_aws_s3"], registry: %{}, store: {MiniRepo.Store.S3, [bucket: "minirepo", options: [region: "ap-southeast-1"]]}, sync_interval: 300000, sync_opts: [max_concurrency: 1], upstream_name: "hexpm", upstream_public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApqREcFDt5vV21JVe2QNB\nEdvzk6w36aNFhVGWN5toNJRjRJ6m4hIuG4KaXtDWVLjnvct6MYMfqhC79HAGwyF+\nIqR6Q6a5bbFSsImgBJwz1oadoVKD6ZNetAuCIK84cjMrEFRkELtEIPNHblCzUkkM\n3rS9+DPlnfG8hBvGi6tvQIuZmXGCxF/73hU0/MyGhbmEjIKRtG6b0sJYKelRLTPW\nXgK7s5pESgiwf2YC/2MGDXjAJfpfCd0RpLdvd4eRiXtVlE9qO9bND94E7PgQ/xqZ\nJ1i2xWFndWa6nfFnRxZmCStCOZWYYPlaxr+FZceFbpMwzTNs4g3d4tLNUcbKAIH4\n0wIDAQAB\n-----END PUBLIC KEY-----\n", upstream_url: "https://repo.hex.pm"}
```

Can we set timeout as config option or can we set it to `infinity`?

**Comment by wojtekmach** [comment]
thank you for your interest in using MiniRepo. FYI: we're deprecating it in favour of an official solution maintained by the Hex team, [`mix hex.registry build`](https://github.com/hexpm/hex/blob/90aa44fa8a1e59f2ae65f490edb984e4d6c853d1/lib/mix/tasks/hex.registry.ex). It's currently only available on Hex master but it is scheduled to be in the next release, Hex v0.21. We also have an upcoming [self-hosting guide](https://github.com/hexpm/hexpm/pull/993/files#diff-602cabbaba27067fae3c0b8f604447b63827e6b7d5b79ed0a720ff558b40b043) to be published on https://hex.pm/docs when the next release is out.

`mix hex.registry build` is only about building the registry files so notably it won't do mirroring for you but it should be relatively easy to build mirroring yourself on top or use mini_repo though the latter will no longer be maintained.

**Comment by collegeimprovements** [comment]
Thanks a lot for your work on `mini_repo` and thanks a lot for letting us know about the future of the project ☺️
Do you still accept pull_requests ?

I can maintain a fork of this project or the main project if required.

**Comment by wojtekmach** [comment]
Yeah, PRs for bug fixes and minor enhancements to existing features are appreciated but probably best to not add new features at the moment. Once we ship Hex v0.21 I'd be looking for folks to take over this project if there's interest so I'll definitely be in touch. Thanks!

**Comment by collegeimprovements** [comment]
Thanks a lot 😃
