### ISSUE TITLE
Minirepo behind a proxy

### ISSUE THREAD

**Issue by sbchand** [wojtekmach/mini_repo#8]
Hello,

I wish to run Minirepo behind a proxy server and use it as a local cache / hex mirror.

With direct internet connectivity (without a proxy server), minirepo starts and automatically fetches packages.  However, if minirepo is behind a proxy, it is not able to reach / fetch packages.  I tried setting environment variables - e.g. "https_proxy" and "HTTPS_PROXY"; however, I felt the environment variables were ignored.

Am I missing anything?  If yes, could you please provide appropriate pointers?

Regards
Bala

**Comment by wojtekmach** [comment]
Yes, these environment variables are ignored.

MiniRepo.Mirror uses [hex_core](https://hex.pm/packages/hex_core) to fetch data from the upstream repository. hex_core ships with a built-in, httpc-based adapter which you can configure like this:

    :httpc.set_options([proxy: {{'proxy.mycompany.com, 8000}, ['localhost']}])

This uses proxy.mycompany.com:8000 as proxy except for requests towards localhost. I'd suggest putting this code in MiniRepo.Application before starting the supervision tree. Let me know if this solves the problem.

A long term solution would be to allow configuring hex_core via mirror configuration, and configuring proxy via hex_core configuration.

**Comment by sbchand** [comment]
I tried your proposal and it works great.  

Thanks very much for your quick and prompt response; highly appreciate it.

Regards
Bala

**Comment by wojtekmach** [comment]
Since this is tracked in hex_core, I'm gonna close it.
